language: python
python:
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
install:
  - pip install -r requirements.txt
env:
  - CODECOV_TOKEN=TOKEN
script:
  - pytest --cov-report xml --cov=mma tests/
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN -f coverage.xml
after_success:
  - codecov
