language: python
python:
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
install:
  - pip install -r requirements.txt
script:
  - pytest --cov-report term --cov=mma tests/
env:
  - CODECOV_TOKEN=TOKEN
after_success:
  - codecov
